# Generated by Django 4.2.8 on 2026-05-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_actor_i_dcd783_idx',
            old_name='audit_audit_actor_id_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_e33994_idx',
            old_name='audit_audit_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_content_4c2ead_idx',
            old_name='audit_audit_contenttypes_app_object_id_idx',
        ),
    ]
