# Generated by Django 4.2.8 on 2026-05-17 20:25

from django.db import migrations


def create_admin_user(apps, schema_editor):
    """Создает администратора и его роль если их нет."""
    User = apps.get_model('auth', 'User')
    UserRole = apps.get_model('accounts', 'UserRole')
    
    # Проверяем есть ли админ
    admin = User.objects.filter(username='admin').first()
    
    if not admin:
        # Создаем админа если его нет
        admin = User.objects.create_superuser(
            username='admin',
            email='admin@mail.ru',
            password='12345'
        )
    
    # Обновляем роль на 'admin' (post_save сигнал создает её с 'client' по умолчанию)
    UserRole.objects.filter(user=admin).update(role='admin')


def reverse_admin_user(apps, schema_editor):
    """Удаляет админа и его роль при откате."""
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_admin_user),
    ]
