# Generated by Django 4.2.8 on 2026-05-17 20:25

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    """Создает профили для всех существующих пользователей если их нет."""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    users = User.objects.all()
    for user in users:
        UserProfile.objects.get_or_create(user=user)


def reverse_user_profiles(apps, schema_editor):
    """Откатывает создание профилей при откате миграции."""
    # Оставляем профили, чтобы не потерять данные
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_admin_user'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_user_profiles),
    ]
