# Generated by Django 4.2.8 on 2026-05-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telemetry',
            new_name='telemetry_t_device__7aed4f_idx',
            old_name='telemetry_t_device_id_recorded_at_idx',
        ),
        migrations.RenameIndex(
            model_name='telemetry',
            new_name='telemetry_t_metric__a062ec_idx',
            old_name='telemetry_t_metric_id_recorded_at_idx',
        ),
        migrations.RenameIndex(
            model_name='telemetry',
            new_name='telemetry_t_recorde_85f705_idx',
            old_name='telemetry_t_recorded_at_idx',
        ),
    ]
