# Generated by Django 4.2.8 on 2026-05-16 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_rename_telemetry_t_device_id_recorded_at_idx_telemetry_t_device__7aed4f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
