# Generated by Django 4.2.8 on 2026-05-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='device',
            new_name='devices_dev_owner_i_d9e88d_idx',
            old_name='devices_dev_owner_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='devices_dev_last_se_c75af6_idx',
            old_name='devices_dev_last_se_idx',
        ),
    ]
