# Generated by Django 4.2.8 on 2026-05-12 21:03

from django.db import migrations
from django.utils import timezone
import uuid


def create_default_device_types_and_devices(apps, schema_editor):
    """Создание типов устройств и демо-устройств с метриками."""
    DeviceType = apps.get_model('devices', 'DeviceType')
    Device = apps.get_model('devices', 'Device')
    DeviceMetric = apps.get_model('devices', 'DeviceMetric')
    User = apps.get_model('auth', 'User')
    
    # Создание типов устройств
    device_types = [
        {'name': 'Датчик температуры', 'description': 'Умный датчик для измерения температуры', 'manufacturer': 'Generic'},
        {'name': 'Датчик влажности', 'description': 'Умный датчик для измерения влажности воздуха', 'manufacturer': 'Generic'},
        {'name': 'Датчик давления', 'description': 'Умный датчик для измерения атмосферного давления', 'manufacturer': 'Generic'},
        {'name': 'Умная розетка', 'description': 'Умная розетка для управления потреблением энергии', 'manufacturer': 'Generic'},
        {'name': 'LED лампа', 'description': 'Умная LED лампа с регулировкой яркости и цвета', 'manufacturer': 'Generic'},
        {'name': 'Контроллер', 'description': 'IoT контроллер для управления другими устройствами', 'manufacturer': 'Generic'},
    ]
    
    type_map = {}
    for device_type in device_types:
        dt, _ = DeviceType.objects.get_or_create(
            name=device_type['name'],
            defaults={
                'description': device_type['description'],
                'manufacturer': device_type['manufacturer'],
            }
        )
        type_map[device_type['name']] = dt
    
    # Получаем существующего админа (создан в миграции accounts)
    owner = User.objects.filter(username='admin').first() or User.objects.filter(is_superuser=True).first() or User.objects.first()
    
    # Создание демонстрационных устройств и метрик
    demo_devices = [
        # 3 датчика температуры
        {
            'name': 'Датчик температуры - Гостиная (T1)',
            'serial_number': 'TEMP-001',
            'device_type': type_map['Датчик температуры'],
            'location_name': 'Гостиная',
            'metadata': {'csv_column': 'T1', 'period_days': 30},
            'metrics': [
                {'metric_type': 'temperature', 'name': 'Температура', 'unit': '°C', 'min_value': -10, 'max_value': 50}
            ]
        },
        {
            'name': 'Датчик температуры - Ванная (T8)',
            'serial_number': 'TEMP-002',
            'device_type': type_map['Датчик температуры'],
            'location_name': 'Ванная',
            'metadata': {'csv_column': 'T8', 'period_days': 30},
            'metrics': [
                {'metric_type': 'temperature', 'name': 'Температура', 'unit': '°C', 'min_value': -10, 'max_value': 50}
            ]
        },
        {
            'name': 'Датчик температуры - Улица (T_out)',
            'serial_number': 'TEMP-003',
            'device_type': type_map['Датчик температуры'],
            'location_name': 'Улица',
            'metadata': {'csv_column': 'T_out', 'period_days': 30},
            'metrics': [
                {'metric_type': 'temperature', 'name': 'Температура', 'unit': '°C', 'min_value': -20, 'max_value': 40}
            ]
        },
        # 2 датчика влажности
        {
            'name': 'Датчик влажности - Гостиная (RH_1)',
            'serial_number': 'HUM-001',
            'device_type': type_map['Датчик влажности'],
            'location_name': 'Гостиная',
            'metadata': {'csv_column': 'RH_1', 'period_days': 30},
            'metrics': [
                {'metric_type': 'humidity', 'name': 'Влажность', 'unit': '%', 'min_value': 0, 'max_value': 100}
            ]
        },
        {
            'name': 'Датчик влажности - Кухня (RH_3)',
            'serial_number': 'HUM-002',
            'device_type': type_map['Датчик влажности'],
            'location_name': 'Кухня',
            'metadata': {'csv_column': 'RH_3', 'period_days': 30},
            'metrics': [
                {'metric_type': 'humidity', 'name': 'Влажность', 'unit': '%', 'min_value': 0, 'max_value': 100}
            ]
        },
        # 1 датчик давления
        {
            'name': 'Датчик давления',
            'serial_number': 'PRES-001',
            'device_type': type_map['Датчик давления'],
            'location_name': 'Основной',
            'metadata': {'csv_column': 'Press_mm_hg', 'period_days': 30},
            'metrics': [
                {'metric_type': 'custom', 'name': 'Давление', 'unit': 'мм рт.ст.', 'min_value': 700, 'max_value': 800}
            ]
        },
        # 3 умные розетки
        {
            'name': 'Умная розетка - Период 1',
            'serial_number': 'PLUG-001',
            'device_type': type_map['Умная розетка'],
            'location_name': 'Жилая комната',
            'metadata': {'csv_column': 'Appliances', 'period_days': 30, 'period_number': 1},
            'metrics': [
                {'metric_type': 'power', 'name': 'Энергопотребление', 'unit': 'Wh', 'min_value': 0, 'max_value': 2000}
            ]
        },
        {
            'name': 'Умная розетка - Период 2',
            'serial_number': 'PLUG-002',
            'device_type': type_map['Умная розетка'],
            'location_name': 'Спальня',
            'metadata': {'csv_column': 'Appliances', 'period_days': 30, 'period_number': 2},
            'metrics': [
                {'metric_type': 'power', 'name': 'Энергопотребление', 'unit': 'Wh', 'min_value': 0, 'max_value': 2000}
            ]
        },
        {
            'name': 'Умная розетка - Период 3',
            'serial_number': 'PLUG-003',
            'device_type': type_map['Умная розетка'],
            'location_name': 'Кухня',
            'metadata': {'csv_column': 'Appliances', 'period_days': 30, 'period_number': 3},
            'metrics': [
                {'metric_type': 'power', 'name': 'Энергопотребление', 'unit': 'Wh', 'min_value': 0, 'max_value': 2000}
            ]
        },
        # 1 LED лампа
        {
            'name': 'LED лампа - Гостиная',
            'serial_number': 'LED-001',
            'device_type': type_map['LED лампа'],
            'location_name': 'Гостиная',
            'metadata': {'csv_column': 'lights', 'period_days': 30},
            'metrics': [
                {'metric_type': 'custom', 'name': 'Освещенность', 'unit': 'Wh', 'min_value': 0, 'max_value': 800}
            ]
        },
    ]
    
    # Создание устройств и метрик
    for device_data in demo_devices:
        metrics_data = device_data.pop('metrics')
        device, _ = Device.objects.get_or_create(
            serial_number=device_data['serial_number'],
            defaults={
                'name': device_data['name'],
                'device_type': device_data['device_type'],
                'location_name': device_data.get('location_name', ''),
                'metadata': device_data.get('metadata', {}),
                'owner': owner,
                'status': 'active',
                'is_active': True,
                'installation_date': timezone.now(),
            }
        )
        
        # Создание метрик для устройства
        for metric_data in metrics_data:
            DeviceMetric.objects.get_or_create(
                device=device,
                metric_type=metric_data['metric_type'],
                defaults={
                    'name': metric_data['name'],
                    'unit': metric_data.get('unit', ''),
                    'min_value': metric_data.get('min_value'),
                    'max_value': metric_data.get('max_value'),
                    'is_active': True,
                }
            )


def reverse_create_device_types_and_devices(apps, schema_editor):
    """Удаление типов устройств и устройств при откате миграции."""
    Device = apps.get_model('devices', 'Device')
    DeviceType = apps.get_model('devices', 'DeviceType')
    Device.objects.all().delete()
    DeviceType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rename_devices_dev_owner_id_status_idx_devices_dev_owner_i_d9e88d_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_device_types_and_devices, reverse_create_device_types_and_devices),
    ]
