# Generated by Django 4.2.8 on 2026-05-12 21:03

from django.db import migrations


def create_default_device_types(apps, schema_editor):
    """Создание типов устройств по умолчанию."""
    DeviceType = apps.get_model('devices', 'DeviceType')
    
    device_types = [
        {'name': 'Датчик температуры', 'description': 'Умный датчик для измерения температуры', 'manufacturer': 'Generic'},
        {'name': 'Датчик влажности', 'description': 'Умный датчик для измерения влажности воздуха', 'manufacturer': 'Generic'},
        {'name': 'Датчик давления', 'description': 'Умный датчик для измерения атмосферного давления', 'manufacturer': 'Generic'},
        {'name': 'Умная розетка', 'description': 'Умная розетка для управления потреблением энергии', 'manufacturer': 'Generic'},
        {'name': 'LED лампа', 'description': 'Умная LED лампа с регулировкой яркости и цвета', 'manufacturer': 'Generic'},
        {'name': 'Контроллер', 'description': 'IoT контроллер для управления другими устройствами', 'manufacturer': 'Generic'},
    ]
    
    for device_type in device_types:
        DeviceType.objects.get_or_create(
            name=device_type['name'],
            defaults={
                'description': device_type['description'],
                'manufacturer': device_type['manufacturer'],
            }
        )


def reverse_create_device_types(apps, schema_editor):
    """Удаление типов устройств при откате миграции."""
    DeviceType = apps.get_model('devices', 'DeviceType')
    DeviceType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rename_devices_dev_owner_id_status_idx_devices_dev_owner_i_d9e88d_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_device_types, reverse_create_device_types),
    ]
