# Generated by Django 4.2.8 on 2026-05-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alert',
            new_name='alerts_aler_device__ea9f18_idx',
            old_name='alerts_alert_device_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='alerts_aler_severit_f1bbe4_idx',
            old_name='alerts_alert_severity_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='alert',
            new_name='alerts_aler_created_574618_idx',
            old_name='alerts_alert_created_at_idx',
        ),
    ]
