# Generated by Django 4.2.8 on 2026-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_alerts_alert_device_id_status_idx_alerts_aler_device__ea9f18_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(choices=[('threshold', 'Порог'), ('ml_anomaly', 'ML-аномалия'), ('ml_forecast', 'ML-прогноз')], db_index=True, default='threshold', max_length=20),
        ),
    ]
